name: custom_calendar_view
description: A Flutter package allows you to easily implement all calendar UI and calendar event functionality.
version: 0.0.9
homepage: https://github.com/nkchouhan/custom_calendar_view.git

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
